name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deployment-buld-docker-img:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker build . -t farmankhan99/devops:latest
      - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - run: docker push farmankhan99/devops:latest
